blank_issues_enabled: false
contact_links:
  - name: 📦 订阅中心
    url: https://simpread.pro/subscribe
    about: |
      我每周都会推 3 ~ 4 篇关于简悦的新功能、联动等内容，建议简悦用户（尤其是经常使用简悦高级功能的用户）订阅【发布汇总】。
  - name: 📚 简悦手册
    url: https://www.yuque.com/kenshin/simpread/
    about: |
      简悦的阅读模式相关功能是不需要设置的。
      如果你使用了更高级的功能，如：同步助手，或者你是 Obsidian / Logseq 等双链笔记用户，或者你本地快照等功能的话，则需要配置。
      简悦官方已经准备好了相关的教程。
  - name: 📦 配置库（强烈建议双链笔记用户使用此方式）
    url: https://www.yuque.com/kenshin/simpread/ds8zk0
    about: |
      这是简悦官方推出的免配置包方案，包括：Notion / Obsidian / Logseq 等用法。
  - name: 📗 Notion 配置库
    url: https://www.yuque.com/kenshin/simpread/mwda8s
    about: |
      通过简悦导入到 Notion 的内容包括：Notion 图床、题图、Favicon、标签等诸多功能。
  - name: 📘 Obsidian 配置库
    url: https://www.yuque.com/kenshin/simpread/psugef
    about: |
      简悦与 Obsidian 的联动可以将简悦的标注系统内置到 Obsidian 中。
  - name: 🖥 如何配置同步助手
    url: https://www.yuque.com/kenshin/simpread/pwpnsx
    about: |
      同步助手相当于一个基于用户系统的服务器，可以实现诸多高级功能（如果你只是阅读模式用户，不需要这些）
  - name: 💾 如何配置本地快照系统
    url: https://www.yuque.com/kenshin/simpread/wkswh7
    about: |
      简悦最大的优势在于：用户拥有全部的数据所有权，只需要简单的几步就能实现一个基于本地的快照系统。
  - name: 👤 高级账户相关功能
    url: https://www.yuque.com/kenshin/simpread/xs0gp0
    about: |
      这是简悦的高级账户相关操作，基本上你出现的问题大部分都可以通过此方式解决。
  - name: 🔒 首次绑定高级账户仍出现带🔒的问题
    url: https://www.yuque.com/kenshin/simpread/xs0gp0
    about: |
      首次升级为高级账户后，请重启浏览器，如果没有重启的话，请使用此链接解决。
  - name: 1️⃣ 如何找回丢失的 UID （高级账户资格）
    url: https://www.yuque.com/kenshin/simpread/bvcunx
    about: |
      如果不小心丢失了 UID 请通过此教程找回。
  - name: 2️⃣ 找回 UID 后如何恢复高级账户资格
    url: https://www.yuque.com/kenshin/simpread/pkq3d1
    about: |
      找回 UID 后可使用此教程恢复你的高级账户资格。
  - name: 3️⃣ 在哪里可以重新找到 License（兑换码）
    url: https://www.yuque.com/kenshin/simpread/hgvw56
    about: |
      找回 UID 前需要知道你的 License，一般来说当升级高级账户后会自动下载含有高级账户 UID 与 License 到本地。
  - name: 📗 Notion 相关问题
    url: https://www.yuque.com/kenshin/simpread/wwk65u
    about: |
      如：无法授权到 Notion，使用导入到 Notion 辅助增强插件失败等常规性问题。
  - name: 🆘 无法打开简悦的选项页或稍后读
    url: https://www.yuque.com/kenshin/simpread/lwuterg3u83sq0b2
    about: |
      如：一般来说只有使用了同步助手后才会遇到此类问题，可通过此链接解决。
