blank_issues_enabled: false
contact_links:
  - name: ç®€æ‚¦æ‰‹å†Œ
    url: https://www.yuque.com/kenshin/simpread/
    about: |
      ç®€æ‚¦çš„é˜…è¯»æ¨¡å¼ç›¸å…³åŠŸèƒ½æ˜¯ä¸éœ€è¦è®¾ç½®çš„ã€‚
      å¦‚æœä½ ä½¿ç”¨äº†æ›´é«˜çº§çš„åŠŸèƒ½ï¼Œå¦‚ï¼šåŒæ­¥åŠ©æ‰‹ï¼Œæˆ–è€…ä½ æ˜¯ Obsidian / Logseq ç­‰åŒé“¾ç¬”è®°ç”¨æˆ·ï¼Œæˆ–è€…ä½ æœ¬åœ°å¿«ç…§ç­‰åŠŸèƒ½çš„è¯ï¼Œåˆ™éœ€è¦é…ç½®ã€‚
      ç®€æ‚¦å®˜æ–¹å·²ç»å‡†å¤‡å¥½äº†ç›¸å…³çš„æ•™ç¨‹ã€‚
  - name: é…ç½®åº“ï¼ˆå¼ºçƒˆå»ºè®®åŒé“¾ç¬”è®°ç”¨æˆ·ä½¿ç”¨æ­¤æ–¹å¼ï¼‰
    url: https://www.yuque.com/kenshin/simpread/ds8zk0
    about: |
      è¿™æ˜¯ç®€æ‚¦å®˜æ–¹æ¨å‡ºçš„å…é…ç½®åŒ…æ–¹æ¡ˆï¼ŒåŒ…æ‹¬ï¼šNotion / Obsidian / Logseq ç­‰ç”¨æ³•
  - name: é«˜çº§è´¦æˆ·ç›¸å…³åŠŸèƒ½
    url: https://www.yuque.com/kenshin/simpread/xs0gp0
    about: |
      è¿™æ˜¯ç®€æ‚¦çš„é«˜çº§è´¦æˆ·ç›¸å…³æ“ä½œï¼ŒåŸºæœ¬ä¸Šä½ å‡ºç°çš„é—®é¢˜å¤§éƒ¨åˆ†éƒ½å¯ä»¥é€šè¿‡æ­¤æ–¹å¼è§£å†³ã€‚
  - name: é¦–æ¬¡ç»‘å®šé«˜çº§è´¦æˆ·ä»å‡ºç°å¸¦ğŸ”’çš„é—®é¢˜
    url: https://www.yuque.com/kenshin/simpread/xs0gp0
    about: |
      é¦–æ¬¡å‡çº§ä¸ºé«˜çº§è´¦æˆ·åï¼Œè¯·é‡å¯æµè§ˆå™¨ï¼Œå¦‚æœæ²¡æœ‰é‡å¯çš„è¯ï¼Œè¯·ä½¿ç”¨æ­¤é“¾æ¥è§£å†³ã€‚
  - name: å¦‚ä½•æ‰¾å›ä¸¢å¤±çš„ UID ï¼ˆé«˜çº§è´¦æˆ·èµ„æ ¼ï¼‰
    url: https://www.yuque.com/kenshin/simpread/bvcunx
    about: |
      å¦‚æœä¸å°å¿ƒä¸¢å¤±äº† UID è¯·é€šè¿‡æ­¤æ•™ç¨‹æ‰¾å›ã€‚
  - name: æ‰¾å› UID åå¦‚ä½•æ¢å¤é«˜çº§è´¦æˆ·èµ„æ ¼
    url: https://www.yuque.com/kenshin/simpread/pkq3d1
    about: |
      æ‰¾å› UID åå¯ä½¿ç”¨æ­¤æ•™ç¨‹æ¢å¤ä½ çš„é«˜çº§è´¦æˆ·èµ„æ ¼ã€‚
  - name: åœ¨å“ªé‡Œå¯ä»¥é‡æ–°æ‰¾åˆ° Licenseï¼ˆå…‘æ¢ç ï¼‰
    url: https://www.yuque.com/kenshin/simpread/hgvw56
    about: |
      æ‰¾å› UID å‰éœ€è¦çŸ¥é“ä½ çš„ Licenseï¼Œä¸€èˆ¬æ¥è¯´å½“å‡çº§é«˜çº§è´¦æˆ·åä¼šè‡ªåŠ¨ä¸‹è½½å«æœ‰é«˜çº§è´¦æˆ· UID ä¸ License åˆ°æœ¬åœ°ã€‚
